// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exdmp.proto

package tencent;

public final class ExDMPRequestMsg {
  private ExDMPRequestMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExDMPRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tencent.ExDMPRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    java.lang.String getUserId();
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>repeated string group_id = 2;</code>
     *
     * <pre>
     *希望查询的用户人群包，查询多个即重复多次
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getGroupIdList();
    /**
     * <code>repeated string group_id = 2;</code>
     *
     * <pre>
     *希望查询的用户人群包，查询多个即重复多次
     * </pre>
     */
    int getGroupIdCount();
    /**
     * <code>repeated string group_id = 2;</code>
     *
     * <pre>
     *希望查询的用户人群包，查询多个即重复多次
     * </pre>
     */
    java.lang.String getGroupId(int index);
    /**
     * <code>repeated string group_id = 2;</code>
     *
     * <pre>
     *希望查询的用户人群包，查询多个即重复多次
     * </pre>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes(int index);
  }
  /**
   * Protobuf type {@code tencent.ExDMPRequest}
   */
  public static final class ExDMPRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tencent.ExDMPRequest)
      ExDMPRequestOrBuilder {
    // Use ExDMPRequest.newBuilder() to construct.
    private ExDMPRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExDMPRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExDMPRequest defaultInstance;
    public static ExDMPRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ExDMPRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExDMPRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                groupId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              groupId_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          groupId_ = groupId_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tencent.ExDMPRequestMsg.ExDMPRequest.class, tencent.ExDMPRequestMsg.ExDMPRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ExDMPRequest> PARSER =
        new com.google.protobuf.AbstractParser<ExDMPRequest>() {
      public ExDMPRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExDMPRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExDMPRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList groupId_;
    /**
     * <code>repeated string group_id = 2;</code>
     *
     * <pre>
     *希望查询的用户人群包，查询多个即重复多次
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getGroupIdList() {
      return groupId_;
    }
    /**
     * <code>repeated string group_id = 2;</code>
     *
     * <pre>
     *希望查询的用户人群包，查询多个即重复多次
     * </pre>
     */
    public int getGroupIdCount() {
      return groupId_.size();
    }
    /**
     * <code>repeated string group_id = 2;</code>
     *
     * <pre>
     *希望查询的用户人群包，查询多个即重复多次
     * </pre>
     */
    public java.lang.String getGroupId(int index) {
      return groupId_.get(index);
    }
    /**
     * <code>repeated string group_id = 2;</code>
     *
     * <pre>
     *希望查询的用户人群包，查询多个即重复多次
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes(int index) {
      return groupId_.getByteString(index);
    }

    private void initFields() {
      userId_ = "";
      groupId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      for (int i = 0; i < groupId_.size(); i++) {
        output.writeBytes(2, groupId_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < groupId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(groupId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getGroupIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tencent.ExDMPRequestMsg.ExDMPRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tencent.ExDMPRequestMsg.ExDMPRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tencent.ExDMPRequestMsg.ExDMPRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tencent.ExDMPRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tencent.ExDMPRequest)
        tencent.ExDMPRequestMsg.ExDMPRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tencent.ExDMPRequestMsg.ExDMPRequest.class, tencent.ExDMPRequestMsg.ExDMPRequest.Builder.class);
      }

      // Construct using tencent.ExDMPRequestMsg.ExDMPRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPRequest_descriptor;
      }

      public tencent.ExDMPRequestMsg.ExDMPRequest getDefaultInstanceForType() {
        return tencent.ExDMPRequestMsg.ExDMPRequest.getDefaultInstance();
      }

      public tencent.ExDMPRequestMsg.ExDMPRequest build() {
        tencent.ExDMPRequestMsg.ExDMPRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tencent.ExDMPRequestMsg.ExDMPRequest buildPartial() {
        tencent.ExDMPRequestMsg.ExDMPRequest result = new tencent.ExDMPRequestMsg.ExDMPRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          groupId_ = groupId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.groupId_ = groupId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tencent.ExDMPRequestMsg.ExDMPRequest) {
          return mergeFrom((tencent.ExDMPRequestMsg.ExDMPRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tencent.ExDMPRequestMsg.ExDMPRequest other) {
        if (other == tencent.ExDMPRequestMsg.ExDMPRequest.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.groupId_.isEmpty()) {
          if (groupId_.isEmpty()) {
            groupId_ = other.groupId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureGroupIdIsMutable();
            groupId_.addAll(other.groupId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tencent.ExDMPRequestMsg.ExDMPRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tencent.ExDMPRequestMsg.ExDMPRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList groupId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGroupIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          groupId_ = new com.google.protobuf.LazyStringArrayList(groupId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getGroupIdList() {
        return groupId_.getUnmodifiableView();
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public int getGroupIdCount() {
        return groupId_.size();
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public java.lang.String getGroupId(int index) {
        return groupId_.get(index);
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes(int index) {
        return groupId_.getByteString(index);
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public Builder setGroupId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupIdIsMutable();
        groupId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public Builder addGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupIdIsMutable();
        groupId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public Builder addAllGroupId(
          java.lang.Iterable<java.lang.String> values) {
        ensureGroupIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public Builder clearGroupId() {
        groupId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string group_id = 2;</code>
       *
       * <pre>
       *希望查询的用户人群包，查询多个即重复多次
       * </pre>
       */
      public Builder addGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupIdIsMutable();
        groupId_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tencent.ExDMPRequest)
    }

    static {
      defaultInstance = new ExDMPRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tencent.ExDMPRequest)
  }

  public interface ExDMPResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tencent.ExDMPResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    java.lang.String getUserId();
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    java.util.List<tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult> 
        getResultList();
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult getResult(int index);
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    int getResultCount();
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    java.util.List<? extends tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder> 
        getResultOrBuilderList();
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder getResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tencent.ExDMPResponse}
   */
  public static final class ExDMPResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tencent.ExDMPResponse)
      ExDMPResponseOrBuilder {
    // Use ExDMPResponse.newBuilder() to construct.
    private ExDMPResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExDMPResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExDMPResponse defaultInstance;
    public static ExDMPResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ExDMPResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExDMPResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userId_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                result_ = new java.util.ArrayList<tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult>();
                mutable_bitField0_ |= 0x00000002;
              }
              result_.add(input.readMessage(tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tencent.ExDMPRequestMsg.ExDMPResponse.class, tencent.ExDMPRequestMsg.ExDMPResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ExDMPResponse> PARSER =
        new com.google.protobuf.AbstractParser<ExDMPResponse>() {
      public ExDMPResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExDMPResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExDMPResponse> getParserForType() {
      return PARSER;
    }

    public interface ExDMPUserGroupResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tencent.ExDMPResponse.ExDMPUserGroupResult)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string group_id = 1;</code>
       *
       * <pre>
       *用户人群包标识
       * </pre>
       */
      boolean hasGroupId();
      /**
       * <code>required string group_id = 1;</code>
       *
       * <pre>
       *用户人群包标识
       * </pre>
       */
      java.lang.String getGroupId();
      /**
       * <code>required string group_id = 1;</code>
       *
       * <pre>
       *用户人群包标识
       * </pre>
       */
      com.google.protobuf.ByteString
          getGroupIdBytes();

      /**
       * <code>required uint32 status = 2;</code>
       *
       * <pre>
       *用户是否在这个人群包, 0表示不在，1表示在，2表示没有cookiemapping，3表示无权限查询
       * </pre>
       */
      boolean hasStatus();
      /**
       * <code>required uint32 status = 2;</code>
       *
       * <pre>
       *用户是否在这个人群包, 0表示不在，1表示在，2表示没有cookiemapping，3表示无权限查询
       * </pre>
       */
      int getStatus();
    }
    /**
     * Protobuf type {@code tencent.ExDMPResponse.ExDMPUserGroupResult}
     */
    public static final class ExDMPUserGroupResult extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:tencent.ExDMPResponse.ExDMPUserGroupResult)
        ExDMPUserGroupResultOrBuilder {
      // Use ExDMPUserGroupResult.newBuilder() to construct.
      private ExDMPUserGroupResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ExDMPUserGroupResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ExDMPUserGroupResult defaultInstance;
      public static ExDMPUserGroupResult getDefaultInstance() {
        return defaultInstance;
      }

      public ExDMPUserGroupResult getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ExDMPUserGroupResult(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                groupId_ = bs;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                status_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.class, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder.class);
      }

      public static com.google.protobuf.Parser<ExDMPUserGroupResult> PARSER =
          new com.google.protobuf.AbstractParser<ExDMPUserGroupResult>() {
        public ExDMPUserGroupResult parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ExDMPUserGroupResult(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ExDMPUserGroupResult> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int GROUP_ID_FIELD_NUMBER = 1;
      private java.lang.Object groupId_;
      /**
       * <code>required string group_id = 1;</code>
       *
       * <pre>
       *用户人群包标识
       * </pre>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string group_id = 1;</code>
       *
       * <pre>
       *用户人群包标识
       * </pre>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            groupId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string group_id = 1;</code>
       *
       * <pre>
       *用户人群包标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATUS_FIELD_NUMBER = 2;
      private int status_;
      /**
       * <code>required uint32 status = 2;</code>
       *
       * <pre>
       *用户是否在这个人群包, 0表示不在，1表示在，2表示没有cookiemapping，3表示无权限查询
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 status = 2;</code>
       *
       * <pre>
       *用户是否在这个人群包, 0表示不在，1表示在，2表示没有cookiemapping，3表示无权限查询
       * </pre>
       */
      public int getStatus() {
        return status_;
      }

      private void initFields() {
        groupId_ = "";
        status_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasGroupId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasStatus()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getGroupIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, status_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getGroupIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, status_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tencent.ExDMPResponse.ExDMPUserGroupResult}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:tencent.ExDMPResponse.ExDMPUserGroupResult)
          tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.class, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder.class);
        }

        // Construct using tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          groupId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          status_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_descriptor;
        }

        public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult getDefaultInstanceForType() {
          return tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.getDefaultInstance();
        }

        public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult build() {
          tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult buildPartial() {
          tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult result = new tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.groupId_ = groupId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.status_ = status_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult) {
            return mergeFrom((tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult other) {
          if (other == tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.getDefaultInstance()) return this;
          if (other.hasGroupId()) {
            bitField0_ |= 0x00000001;
            groupId_ = other.groupId_;
            onChanged();
          }
          if (other.hasStatus()) {
            setStatus(other.getStatus());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasGroupId()) {
            
            return false;
          }
          if (!hasStatus()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object groupId_ = "";
        /**
         * <code>required string group_id = 1;</code>
         *
         * <pre>
         *用户人群包标识
         * </pre>
         */
        public boolean hasGroupId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string group_id = 1;</code>
         *
         * <pre>
         *用户人群包标识
         * </pre>
         */
        public java.lang.String getGroupId() {
          java.lang.Object ref = groupId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              groupId_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string group_id = 1;</code>
         *
         * <pre>
         *用户人群包标识
         * </pre>
         */
        public com.google.protobuf.ByteString
            getGroupIdBytes() {
          java.lang.Object ref = groupId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            groupId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string group_id = 1;</code>
         *
         * <pre>
         *用户人群包标识
         * </pre>
         */
        public Builder setGroupId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          groupId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string group_id = 1;</code>
         *
         * <pre>
         *用户人群包标识
         * </pre>
         */
        public Builder clearGroupId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          groupId_ = getDefaultInstance().getGroupId();
          onChanged();
          return this;
        }
        /**
         * <code>required string group_id = 1;</code>
         *
         * <pre>
         *用户人群包标识
         * </pre>
         */
        public Builder setGroupIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          groupId_ = value;
          onChanged();
          return this;
        }

        private int status_ ;
        /**
         * <code>required uint32 status = 2;</code>
         *
         * <pre>
         *用户是否在这个人群包, 0表示不在，1表示在，2表示没有cookiemapping，3表示无权限查询
         * </pre>
         */
        public boolean hasStatus() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint32 status = 2;</code>
         *
         * <pre>
         *用户是否在这个人群包, 0表示不在，1表示在，2表示没有cookiemapping，3表示无权限查询
         * </pre>
         */
        public int getStatus() {
          return status_;
        }
        /**
         * <code>required uint32 status = 2;</code>
         *
         * <pre>
         *用户是否在这个人群包, 0表示不在，1表示在，2表示没有cookiemapping，3表示无权限查询
         * </pre>
         */
        public Builder setStatus(int value) {
          bitField0_ |= 0x00000002;
          status_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 status = 2;</code>
         *
         * <pre>
         *用户是否在这个人群包, 0表示不在，1表示在，2表示没有cookiemapping，3表示无权限查询
         * </pre>
         */
        public Builder clearStatus() {
          bitField0_ = (bitField0_ & ~0x00000002);
          status_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:tencent.ExDMPResponse.ExDMPUserGroupResult)
      }

      static {
        defaultInstance = new ExDMPUserGroupResult(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:tencent.ExDMPResponse.ExDMPUserGroupResult)
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_id = 1;</code>
     *
     * <pre>
     *DSP端用户标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private java.util.List<tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult> result_;
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    public java.util.List<tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    public java.util.List<? extends tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
     *
     * <pre>
     *查询结果
     * </pre>
     */
    public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private void initFields() {
      userId_ = "";
      result_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getResultCount(); i++) {
        if (!getResult(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(2, result_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, result_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tencent.ExDMPRequestMsg.ExDMPResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tencent.ExDMPRequestMsg.ExDMPResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tencent.ExDMPRequestMsg.ExDMPResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tencent.ExDMPResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tencent.ExDMPResponse)
        tencent.ExDMPRequestMsg.ExDMPResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tencent.ExDMPRequestMsg.ExDMPResponse.class, tencent.ExDMPRequestMsg.ExDMPResponse.Builder.class);
      }

      // Construct using tencent.ExDMPRequestMsg.ExDMPResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tencent.ExDMPRequestMsg.internal_static_tencent_ExDMPResponse_descriptor;
      }

      public tencent.ExDMPRequestMsg.ExDMPResponse getDefaultInstanceForType() {
        return tencent.ExDMPRequestMsg.ExDMPResponse.getDefaultInstance();
      }

      public tencent.ExDMPRequestMsg.ExDMPResponse build() {
        tencent.ExDMPRequestMsg.ExDMPResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tencent.ExDMPRequestMsg.ExDMPResponse buildPartial() {
        tencent.ExDMPRequestMsg.ExDMPResponse result = new tencent.ExDMPRequestMsg.ExDMPResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tencent.ExDMPRequestMsg.ExDMPResponse) {
          return mergeFrom((tencent.ExDMPRequestMsg.ExDMPResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tencent.ExDMPRequestMsg.ExDMPResponse other) {
        if (other == tencent.ExDMPRequestMsg.ExDMPResponse.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        for (int i = 0; i < getResultCount(); i++) {
          if (!getResult(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tencent.ExDMPRequestMsg.ExDMPResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tencent.ExDMPRequestMsg.ExDMPResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 1;</code>
       *
       * <pre>
       *DSP端用户标识
       * </pre>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          result_ = new java.util.ArrayList<tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult>(result_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder> resultBuilder_;

      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public java.util.List<tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder setResult(
          int index, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder setResult(
          int index, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder addResult(tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder addResult(
          int index, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder addResult(
          tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder addResult(
          int index, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public java.util.List<? extends tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.getDefaultInstance());
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.getDefaultInstance());
      }
      /**
       * <code>repeated .tencent.ExDMPResponse.ExDMPUserGroupResult result = 2;</code>
       *
       * <pre>
       *查询结果
       * </pre>
       */
      public java.util.List<tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResult.Builder, tencent.ExDMPRequestMsg.ExDMPResponse.ExDMPUserGroupResultOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tencent.ExDMPResponse)
    }

    static {
      defaultInstance = new ExDMPResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tencent.ExDMPResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tencent_ExDMPRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tencent_ExDMPRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tencent_ExDMPResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tencent_ExDMPResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013exdmp.proto\022\007tencent\"1\n\014ExDMPRequest\022\017" +
      "\n\007user_id\030\001 \002(\t\022\020\n\010group_id\030\002 \003(\t\"\227\001\n\rEx" +
      "DMPResponse\022\017\n\007user_id\030\001 \002(\t\022;\n\006result\030\002" +
      " \003(\0132+.tencent.ExDMPResponse.ExDMPUserGr" +
      "oupResult\0328\n\024ExDMPUserGroupResult\022\020\n\010gro" +
      "up_id\030\001 \002(\t\022\016\n\006status\030\002 \002(\rB\021B\017ExDMPRequ" +
      "estMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tencent_ExDMPRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tencent_ExDMPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tencent_ExDMPRequest_descriptor,
        new java.lang.String[] { "UserId", "GroupId", });
    internal_static_tencent_ExDMPResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tencent_ExDMPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tencent_ExDMPResponse_descriptor,
        new java.lang.String[] { "UserId", "Result", });
    internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_descriptor =
      internal_static_tencent_ExDMPResponse_descriptor.getNestedTypes().get(0);
    internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tencent_ExDMPResponse_ExDMPUserGroupResult_descriptor,
        new java.lang.String[] { "GroupId", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
